
USE BaseballData

CREATE TABLE GameTable(
	testId INTEGER NOT NULL,
	gold INTEGER NULL,
	createDate DATETIME NOT NULL,
	PRIMARY KEY(createDate)
)

ALTER TABLE GameTable 
ADD Jem INTEGER

ALTER TABLE GameTable
ADD CONSTRAINT PK_testId PRIMARY KEY(testId)

ALTER TABLE GameTable
DROP COLUMN Jem

ALTER TABLE GameTable
DROP CONSTRAINT PK_testId

ALTER TABLE GameTable
ALTER COLUMN gold FLOAT NULL